from vmgCommanderBase import CommanderBase
from vmgInstallerDummy import InstallerDummy
from runCommands import *
import shutil
import os
import time


def writeNewLine(f):
	f.write("\n")

def writeComment(f, text):
	f.write("# " + text + "\n")

def writeHeader(f, text):
	f.write("#!" + text + "\n")

def writeOption(f, key, value):
	f.write(key + ' = "' + value + '"\n')

def tryWriteOption(f, key, section, conf_key):
	if (section.contains(conf_key)):
		writeOption(f, key, section.get(conf_key))

#vmaster_vmx_orig = "F:\\Virtual Machines\\VMaster\\VMaster.vmx"
#vmaster_vmx = "F:\\Virtual Machines\\VMaster\\VMaster_modified.vmx"
#base_install_dir = "F:\\Virtual Machines\\so-vm-linux-neon\\so_gentoo\\"
#new_machine_dir = os.getcwd() + "\\"
vmaster_vmx_orig = "/home/vmgen/VMaster/VMaster.vmx"
vmaster_vmx = "/home/vmgen/VMaster/VMaster_modified.vmx"
base_install_dir = "/iso-images/"
new_machine_dir = os.getcwd() + "/machines/"

mkfs = { 
		"ntfs":{
			"cmd":"mkfs.ntfs", 
			"id":"7"},
		"ext2":{
			"cmd":"mkfs.ext2",
			"id":"83"},
		"ext3":{
			"cmd":"mkfs.ext3",
			"id":"83"},
		"ext4":{
			"cmd":"mkfs.ext4",
			"id":"83"},
		"swap":{
			"cmd":"mkswap",
			"id":"82"}
		}
#base_disks = {"debian5-64":"debian6-64.vmdk"}
base_disks = {
			"debian5-64":{ 
				"name":"so_gentoo.vmdk",
				"type":"lsilogic",
				"mbr":"grub2",
				"fs":"ext4"},
			"ubuntu-64":{
				"name":"ubuntu-64.vmdk",
				"type":"lsilogic",
				"mbr":"grub2",
				"fs":"ext4"},
			"windows7-64":{
				"name":"Win7-64.vmdk",
				"type":"lsilogic",
				"mbr":"win",
				"fs":"ntfs"},
			"winxppro":{
				"name":"WinXP.vmdk",
				"type":"ide",
				"mbr":"win",
				"fs":"ntfs"}
			}

class CommanderVmware(CommanderBase):
	def startVM(self):
		print "\nStarting the VM..."

	def shutdownVM(self):
		print "\nShutting down the VM..."

	def connectToVM(self):
		print "\nEstablishing connection to the VM..."

	def disconnectFromVM(self):
		print "\nTerminating connection to the VM..."

	def setupHardware(self):
		print "\nCreating the hardware configuration..."
		section = self.data.getSection("hardware")
		self.os = section.get("os")
		vmx_file = new_machine_dir + "machine.vmx"
		with open(vmx_file, "w") as f:
			writeHeader(f, "/usr/bin/vmware")
			writeOption(f, "config.version", "8")
			writeOption(f, "virtualHW.version", "7")
			tryWriteOption(f, "guestOs", section, "os")
			tryWriteOption(f, "displayName", section, "vm_id")
			tryWriteOption(f, "numvcpus", section, "num_cpu")
			tryWriteOption(f, "memsize", section, "ram")
			writeNewLine(f)
			
			# create hard disks
			writeComment(f, "hard-disk")
			self.hdd_list = section.get("hdds").data.values()
			for hdd in self.hdd_list:
				hdd_type = hdd.get("type")
				if hdd_type == "scsi":
					# only for scsi
					adapter = "lsilogic"
					adapter = "lsisas1068"
					hdd_idx = hdd.get("scsi_index")
					writeOption(f, hdd_type+hdd_idx + ".present", "TRUE")
					writeOption(f, hdd_type+hdd_idx + ".virtualDev", adapter)
				else:
					adapter = "ide"

				hdd_size = hdd.get("size")
				hdd_pos = hdd.get("pos")
				hdd_name = hdd.get("name")
				writeOption(f, hdd_type+hdd_pos + ".present", "TRUE")
				writeOption(f, hdd_type+hdd_pos + ".fileName", hdd_name)

				executeCommand("vmware-vdiskmanager -c -s " + hdd_size +
						" -a " + adapter + " -t 0 " + 
						new_machine_dir + hdd_name)

			writeNewLine(f)

			# create cd drives
			writeComment(f, "cd-rom")
			self.cd_list = section.get("cd_drives").data.values()
			for cd in self.cd_list:
				cd_type = "ide"
				cd_pos = cd.get("pos")
				cd_path = cd.get("path")
				writeOption(f, cd_type+cd_pos + ".present", "TRUE")
				writeOption(f, cd_type+cd_pos + ".deviceType", "cdrom-image")
				writeOption(f, cd_type+cd_pos + ".fileName", cd_path)
				tryWriteOption(f, cd_type+cd_pos + ".startConnected", cd, 
						"connected")
			writeNewLine(f)

			writeComment(f, "ethernet")
			self.eth_list = section.get("eths").data.values()
			for i, eth in enumerate(self.eth_list):
				i = str(i)
				eth_name = "ethernet" + i
				eth_type = eth.get("type")
				writeOption(f, eth_name + ".present", "TRUE")
				writeOption(f, eth_name + ".virtualDev", "e1000")
				writeOption(f, eth_name + ".connectionType", eth_type)
				tryWriteOption(f, eth_name + ".startConnected", eth, 
						"connected")
			writeNewLine(f)
			writeComment(f, "auto generated by VMware")

	def setupPartitions(self):
#		section = self.data.getSection("hardware")["hdds"]
		# attach the hdds to VMaster
		shutil.copy2(vmaster_vmx_orig, vmaster_vmx)
		with open(vmaster_vmx, "a") as f:
			# attach the base_system hdd
			disk_name = base_install_dir + base_disks[self.os]["name"]
			disk_type = base_disks[self.os]["type"]

			if disk_type == "ide":
				prefix = "ide0:0"
			else:
				prefix = "scsi0:1"

			writeOption(f, prefix + ".present", "TRUE")
			writeOption(f, prefix + ".fileName", disk_name)
			for i, hdd in enumerate(self.hdd_list):
				hdd_type = hdd.get("type")
				if hdd_type == "scsi":
					hdd_pos = "0:" + str(i + 2)
				else:
					hdd_pos = "0:" + str(i + 1)
				writeOption(f, hdd_type+hdd_pos + ".present", "TRUE")
				writeOption(f, hdd_type+hdd_pos + ".fileName", 
						new_machine_dir + hdd.get("name"))

		# start VMaster
		executeCommand("vmrun start " + '"' + vmaster_vmx + '"')
		time.sleep(30)

		# setup the partitions
		for i, hdd in enumerate(self.hdd_list):
			hdd_name = "/dev/sd" + chr(ord("c") + i)
			i = str(i)
			idx_primary = 0
			idx_logical = 4
			last_off = 1
			executeCommandSSH("parted -s " + hdd_name + " mklabel msdos")
			self.part_list = hdd.get("partitions").data.values()
			for j, part in enumerate(self.part_list):
				j = str(j)
				part_size = int(part.get("size"))
				part_type = part.get("type")

				# update the next index
				if part_type == "primary" or part_type == "extended":
					idx_primary += 1
					crt_idx = idx_primary
				elif part_type == "logical":
					idx_logical += 1
					crt_idx = idx_logical

				executeCommandSSH("parted -s " + hdd_name + " mkpart " + 
						part_type + " " + str(last_off) + " " + 
						str(last_off + part_size))

				executeCommandSSH("hdparm -z " + hdd_name)

				if part_type != "extended":
					last_off += part_size
					part_fs = part.get("fs")
					executeCommandSSH("sfdisk --change-id " + hdd_name + " "
							+ str(crt_idx) + " " + mkfs[part_fs]["id"])
					executeCommandSSH(mkfs[part_fs]["cmd"] + " " + hdd_name 
							+ str(crt_idx))


	def setupOperatingSystem(self):
		print "\nInstalling the operating system..."
		executeCommandSSH("parted -s /dev/sdc set 1 boot on")
		if base_disks[self.os]["fs"] == "ntfs":
			# ntfs
			executeCommandSSH("ntfsclone --overwrite /dev/sdc1 /dev/sdb1")
			executeCommandSSH("ntfsresize --force /dev/sdc1")
		else:
			# other (ext*)
			executeCommandSSH("mount /dev/sdb1 /mnt/old_hdd")
			executeCommandSSH("mount /dev/sdc1 /mnt/new_hdd")
			executeCommandSSH("cp -ax /mnt/old_hdd/* /mnt/new_hdd/")

			uuid_old = executeCommandSSH('blkid /dev/sdb1')[1].split('"')[1]
			executeCommandSSH("tune2fs -U " + uuid_old + " /dev/sdc1")

		if base_disks[self.os]["mbr"] == "grub2":
			executeCommandSSH("grub-setup -d /mnt/new_hdd/boot/grub /dev/sdc")
		else:
			executeCommandSSH("dd if=/dev/sdb of=/dev/sdc bs=446 count=1")


		
		

	def setupConfigurations(self):
		print "\nConfiguring system settings..."
		section = self.data.getSection("config")
		for k, v in section.items():
			print k, "=", v

	def setupNetwork(self):	
		print "\nSetting up the network configurations..."
		section = self.data.getSection("network")
		for k, v in section.items():
			print k, "=", v

	def setupUsers(self):
		print "\nAdding users..."
		section = self.data.getSection("users")
		for i, u in enumerate(section.get("users")):
			print "Add user #"+i
			print "\tName: ", u["name"]
			print "\tPassword: ", u["passwd"]
			print "\tGroup: ", u["group"]
			print "\tHome directory: ", u["home_dir"]
			print "\tPermissions: ", u["perm"]
	
	def setupServices(self):
		print "\nInstalling services..."
		section = self.data.getSection("services")
		self.installPrograms(section)

	def setupDeveloperTools(self):
		print "\nInstalling developer tools..."
		section = self.data.getSection("devel")
		self.installPrograms(section)

	def setupGuiTools(self):
		print "\nInstalling GUI tools..."
		section = self.data.getSection("gui")
		self.installPrograms(section)
	
